import {test,expect} from '@playwright/test';
declare global{interface Window{__railSimDebug:{setRoutePosition(s:number):void;setScenarioTime(value:string):void;operations():{trains:{id:string;active:boolean;edge:string;speed:number;nextStop:string}[];occupied:[string,string[]][];routes:string[]}}}}
test('timetable traffic drives occupancy and authority',async({page})=>{const errors:string[]=[];page.on('console',m=>{if(m.type()==='error')errors.push(m.text())});await page.goto('./?debug=1&s=1000&time=14:15:30&camera=chase');await expect(page.locator('body')).toHaveAttribute('data-sim-ready','true',{timeout:20000});await expect(page.locator('body')).toHaveAttribute('data-ai-trains',/[1-9]/);await expect(page.locator('body')).toHaveAttribute('data-occupied-sections',/[1-9]/);await expect(page.locator('#nearbyTraffic')).toContainText(/11448|11648|2025/);const occupied=await page.evaluate(()=>window.__railSimDebug.operations());expect(occupied.trains.filter(x=>x.active).length).toBeGreaterThanOrEqual(2);expect(occupied.occupied.length).toBeGreaterThan(0);expect(occupied.routes).not.toContain('PLAYER_AUTH');await expect(page.locator('#signal')).toContainText('HALT');await page.evaluate(()=>window.__railSimDebug.setScenarioTime('14:30:00'));await expect(page.locator('#signal')).toContainText('CLEAR');const clear=await page.evaluate(()=>window.__railSimDebug.operations());expect(clear.routes).toContain('PLAYER_AUTH');expect(errors).toEqual([])});

test('scenario restart produces the same traffic state',async({page})=>{await page.goto('./?debug=1&s=9000&time=14:16:00');await expect(page.locator('body')).toHaveAttribute('data-ai-trains',/[1-9]/,{timeout:20000});const before=await page.evaluate(()=>window.__railSimDebug.operations());await page.keyboard.press('r');await page.waitForTimeout(250);const after=await page.evaluate(()=>window.__railSimDebug.operations());expect(after.trains).toEqual(before.trains);expect(after.occupied).toEqual(before.occupied)});

test('normal scenario begins without a train conflict',async({page})=>{await page.goto('./?debug=1&s=0');await expect(page.locator('body')).toHaveAttribute('data-sim-ready','true',{timeout:20000});await page.waitForTimeout(500);expect(await page.locator('body').getAttribute('data-safety')).toBeFalsy()});

test('pause freezes the shared operations clock',async({page})=>{await page.goto('./?debug=1&s=8000&time=14:15:30');await expect(page.locator('body')).toHaveAttribute('data-ai-trains',/[1-9]/,{timeout:20000});await page.keyboard.press('p');await expect(page.locator('body')).toHaveAttribute('data-paused','true');const before=await page.evaluate(()=>window.__railSimDebug.operations());await page.waitForTimeout(500);const after=await page.evaluate(()=>window.__railSimDebug.operations());expect(after).toEqual(before);await page.keyboard.press('p');await expect(page.locator('body')).toHaveAttribute('data-paused','false')});
