import {test,expect} from '@playwright/test';
test('loads corridor, wasm, and enters driving mode',async({page})=>{const errors:string[]=[];page.on('console',m=>{if(m.type()==='error')errors.push(m.text())});await page.goto('./');await expect(page.getByRole('heading',{name:'Rapperswil → Uznach'})).toBeVisible();await page.getByRole('button',{name:'DRIVE'}).click();await expect(page.locator('#start')).toHaveClass(/hidden/);await expect(page.locator('#world canvas')).toBeVisible();await page.keyboard.press('w');await page.waitForTimeout(500);await expect(page.locator('#notch')).toHaveText('P1');await page.getByRole('button',{name:'Brake 3'}).click();await expect(page.locator('#notch')).toHaveText('B3');await page.getByRole('button',{name:'Emergency brake'}).click();await expect(page.locator('#notch')).toHaveText('BE');await page.keyboard.press('c');expect(errors).toEqual([])});

test('pointer dragging synchronizes the combined controller',async({page})=>{await page.goto('./');await expect(page.locator('body')).toHaveAttribute('data-sim-ready','true',{timeout:20000});await page.getByRole('button',{name:'DRIVE'}).click();const gate=page.getByRole('slider');const box=await gate.boundingBox();if(!box)throw Error('controller gate unavailable');await page.mouse.move(box.x+box.width/2,box.y+box.height*.08);await page.mouse.down();await page.mouse.move(box.x+box.width/2,box.y+box.height*.72);await page.mouse.up();await expect(gate).toHaveAttribute('aria-valuenow','-2')});

test('loads the versioned scenery manifest and SWISSIMAGE tiles',async({page})=>{const imagery:string[]=[];page.on('response',r=>{if(r.url().endsWith('.webp')&&r.ok())imagery.push(r.url())});await page.goto('./?debug=1&s=6700');await expect(page.locator('body')).toHaveAttribute('data-imagery','loaded');await expect(page.locator('body')).toHaveAttribute('data-scenery-tiles','4');expect(imagery).toHaveLength(4)});

test('loads landscape layers and a streamed official building tile',async({page})=>{const assets:string[]=[];page.on('response',r=>{if(r.ok()&&(r.url().includes('/buildings/')||r.url().endsWith('/landscape.json')))assets.push(r.url())});await page.goto('./?debug=1&s=6700');await expect(page.locator('body')).toHaveAttribute('data-landscape','loaded');await expect(page.locator('body')).toHaveAttribute('data-building-tiles',/[1-4]/,{timeout:20000});await expect(page.locator('body')).toHaveAttribute('data-buildings',/^[1-9]\d*$/);expect(assets.some(x=>x.endsWith('/landscape.json'))).toBeTruthy();expect(assets.filter(x=>x.includes('/buildings/')).length).toBeGreaterThanOrEqual(2)});

test('minimap and deterministic journey progression remain operational',async({page})=>{await page.goto('./?debug=1&s=1000');await expect(page.locator('body')).toHaveAttribute('data-sim-ready','true',{timeout:20000});await expect(page.locator('#routeMap')).toBeVisible();await expect(page.locator('#journeyProgress')).toContainText('Blumenau');await page.evaluate(()=>window.__railSimDebug.setRoutePosition(11000));await expect(page.locator('#signal')).not.toHaveText('END');await expect(page.locator('#station')).toContainText('Uznach');await page.evaluate(()=>window.__railSimDebug.setRoutePosition(13490));await expect(page.locator('#journeyResult')).not.toHaveClass(/hidden/)});

declare global{interface Window{__railSimDebug:{setRoutePosition(s:number):void}}}
