import * as THREE from 'three';
import init, { TrainSim } from '../pkg/rail_sim_core.js';
import './style.css';

const root=document.querySelector<HTMLDivElement>('#app')!;
root.innerHTML=`<div id="world"></div><div class="hud"><div class="panel brand">OPEN SWISS RAIL SIM</div><div class="panel metrics"><div class="metric"><small>Speed</small><b><span id="speed">0</span> km/h</b></div><div class="metric"><small>Limit</small><b>80 km/h</b></div><div class="metric"><small>Power / brake</small><b id="notch">P0 / B0</b></div><div class="metric"><small>Gradient</small><b id="grade">0.0 ‰</b></div></div></div><div class="panel controls">W / ↑ power · S / ↓ brake · A release · Space emergency · C camera · R restart</div><div class="panel notice"><span class="tag">Corridor</span> Swiss demo alignment · data inspector: <span class="derived">derived preview</span></div><section class="start" id="start"><div class="panel card"><span class="tag">OPEN DATA DRIVING SIMULATOR</span><h1>Real geography.<br>Simulated operations.</h1><p>Drive a generic Swiss electric passenger train. Infrastructure provenance remains visible at every layer.</p><div class="coverage"><span>Terrain / alignment</span><b class="derived">PREVIEW → REAL DATA PIPELINE</b><span>Train physics</span><b class="sim">SIMULATED IN RUST/WASM</b><span>Signal state</span><b class="sim">SIMULATED</b></div><button id="drive">DRIVE</button></div></section>`;

await init();
const sim=new TrainSim(); let power=0,brake=0,cameraMode=0,last=performance.now(),acc=0;
const scene=new THREE.Scene(); scene.background=new THREE.Color(0x9ab5bd); scene.fog=new THREE.Fog(0x9ab5bd,500,4000);
const camera=new THREE.PerspectiveCamera(65,innerWidth/innerHeight,.1,6000);
const renderer=new THREE.WebGLRenderer({antialias:true}); renderer.setPixelRatio(Math.min(devicePixelRatio,2)); renderer.setSize(innerWidth,innerHeight); renderer.shadowMap.enabled=true; document.querySelector('#world')!.append(renderer.domElement);
scene.add(new THREE.HemisphereLight(0xddecff,0x30452f,2)); const sun=new THREE.DirectionalLight(0xfff1d1,2.5);sun.position.set(-400,900,-300);scene.add(sun);
const terrainGeo=new THREE.PlaneGeometry(5000,16000,60,160); const pos=terrainGeo.attributes.position; for(let i=0;i<pos.count;i++){const x=pos.getX(i),y=pos.getY(i);pos.setZ(i,25*Math.sin(x/380)+38*Math.sin(y/900)+15*Math.sin((x+y)/210));} terrainGeo.rotateX(-Math.PI/2); terrainGeo.computeVertexNormals(); const terrain=new THREE.Mesh(terrainGeo,new THREE.MeshStandardMaterial({color:0x547b4e,roughness:1}));terrain.position.z=-5000;scene.add(terrain);
const route=new THREE.CatmullRomCurve3(Array.from({length:45},(_,i)=>{const z=i*220-5000;return new THREE.Vector3(90*Math.sin(i*.18),42+25*Math.sin((z+5000)/900),z)}));
for(const dx of [-.72,.72]){const tube=new THREE.TubeGeometry(route,900,.075,5,false);const rail=new THREE.Mesh(tube,new THREE.MeshStandardMaterial({color:0xbcc1bf,metalness:.8,roughness:.3}));rail.position.x=dx;scene.add(rail)}
for(let i=0;i<600;i++){const p=route.getPoint(i/600);const sleeper=new THREE.Mesh(new THREE.BoxGeometry(2.6,.12,.22),new THREE.MeshStandardMaterial({color:0x47372b}));sleeper.position.copy(p);scene.add(sleeper)}
const train=new THREE.Group();const body=new THREE.Mesh(new THREE.BoxGeometry(3,3.6,24),new THREE.MeshStandardMaterial({color:0xd8ddd9,roughness:.45}));body.position.y=2.3;train.add(body);const nose=new THREE.Mesh(new THREE.BoxGeometry(3.05,1.2,5),new THREE.MeshStandardMaterial({color:0xc72f2d}));nose.position.set(0,1.6,-9.5);train.add(nose);scene.add(train);
const keys=(e:KeyboardEvent)=>{if(e.repeat)return;if(['w','ArrowUp'].includes(e.key)){power=Math.min(5,power+1);brake=0}if(['s','ArrowDown'].includes(e.key)){brake=Math.min(5,brake+1);power=0}if(e.key==='a'){power=Math.max(0,power-1);brake=Math.max(0,brake-1)}if(e.code==='Space'){brake=6;power=0}if(e.key==='r'){sim.reset();power=brake=0}if(e.key==='c')cameraMode=(cameraMode+1)%2};addEventListener('keydown',keys);document.querySelector('#drive')!.addEventListener('click',()=>document.querySelector('#start')!.classList.add('hidden'));
function frame(now:number){const delta=Math.min((now-last)/1000,.1);last=now;acc+=delta;const routeM=Math.max(0,Math.min(9900,sim.position()));const grad=10*Math.cos(routeM/900);sim.set_controls(power,brake);while(acc>=1/120){sim.step(1/120,grad);acc-=1/120}const t=Math.min(.999,sim.position()/9900);const p=route.getPointAt(t),ahead=route.getPointAt(Math.min(.999,t+.002));train.position.copy(p);train.lookAt(ahead);if(cameraMode===0){camera.position.copy(p).add(new THREE.Vector3(0,4.2,2));camera.lookAt(ahead.clone().add(new THREE.Vector3(0,2.4,0)))}else{camera.position.lerp(p.clone().add(new THREE.Vector3(18,10,32)),.08);camera.lookAt(p)}document.querySelector('#speed')!.textContent=(sim.speed()*3.6).toFixed(0);document.querySelector('#notch')!.textContent=`P${power} / B${brake===6?'E':brake}`;document.querySelector('#grade')!.textContent=`${grad.toFixed(1)} ‰`;renderer.render(scene,camera);requestAnimationFrame(frame)}requestAnimationFrame(frame);
addEventListener('resize',()=>{camera.aspect=innerWidth/innerHeight;camera.updateProjectionMatrix();renderer.setSize(innerWidth,innerHeight)});

