import * as THREE from 'three';
import init,{TrainSim} from '../pkg/rail_sim_core.js';
import {TrackFrameSampler} from './track-frame';
import './style.css';

type Obj={id:number;s:number;tags:Record<string,string>};
type Data={points:{x:number;y:number;z:number}[];signals:Obj[];stations:Obj[];speedLimits:{start:number;end:number;speed:number}[]};
type TerrainData={originX:number;originZ:number;spacingM:number;width:number;height:number;heights:number[];stats:{vertices:number;triangles:number}};
const getJson=async<T>(path:string)=>fetch(path).then(r=>{if(!r.ok)throw Error(`${path} ${r.status}`);return r.json() as Promise<T>});
const [data,terrain]=await Promise.all([getJson<Data>('./data/rapperswil-uznach/route.json'),getJson<TerrainData>('./data/rapperswil-uznach/terrain.json')]);await init();
const params=new URLSearchParams(location.search),debug=params.get('debug')==='1',fixedS=params.has('s')?Number(params.get('s')):null;
document.querySelector('#app')!.innerHTML=`<div id="world"></div><div class="hud"><div class="panel brand">OPEN SWISS RAIL SIM</div><div class="panel metrics"><div class="metric"><small>Speed</small><b><span id="speed">0</span> km/h</b></div><div class="metric"><small>Limit</small><b><span id="limit">—</span> km/h</b></div><div class="metric"><small>Power / brake</small><b id="notch">P0 / B0</b></div><div class="metric"><small>Gradient</small><b id="grade">0.0 ‰</b></div><div class="metric"><small>Next signal</small><b id="signal">—</b></div><div class="metric"><small>Next station</small><b id="station">—</b></div></div></div><div class="panel controls">W / ↑ power · S / ↓ brake · A release · Space emergency · C camera · R restart</div><button class="panel dataBtn" id="dataBtn">ABOUT / DATA</button><aside class="panel inspector hidden" id="inspector"><button id="close">×</button><h2>Data provenance</h2><p><b class="real">REAL</b> swissALTI3D elevation, OSM alignment, mapped longitudinal signal/station positions and speeds.</p><p><b class="derived">DERIVED</b> track frame, rail/terrain meshes, inferred lateral signal placement and catenary.</p><p><b class="sim">SIMULATED</b> aspects, block state, train dynamics, energy and score.</p><hr><div id="details"></div><small>© swisstopo · © OpenStreetMap contributors (ODbL)</small></aside><section class="start" id="start"><div class="panel card"><span class="tag">OPEN DATA DRIVING SIMULATOR</span><h1>Rapperswil → Uznach</h1><p>13.47 km through the Linth plain on real Swiss terrain and mapped railway infrastructure.</p><div class="coverage"><span>Terrain / alignment</span><b class="real">REAL OPEN DATA</b><span>Signals</span><b class="derived">26 MAPPED / ASPECTS SIMULATED</b><span>Train physics</span><b class="sim">SIMULATED IN RUST/WASM</b></div><button id="drive">DRIVE</button></div></section>${debug?'<div class="debugStats panel" id="debugStats"></div>':''}`;
const scene=new THREE.Scene();scene.background=new THREE.Color(0xabc4cc);scene.fog=new THREE.FogExp2(0xabc4cc,.00024);
const camera=new THREE.PerspectiveCamera(64,innerWidth/innerHeight,.1,6000),renderer=new THREE.WebGLRenderer({antialias:true});renderer.setPixelRatio(Math.min(devicePixelRatio,1.7));renderer.setSize(innerWidth,innerHeight);renderer.toneMapping=THREE.ACESFilmicToneMapping;document.querySelector('#world')!.append(renderer.domElement);scene.add(new THREE.HemisphereLight(0xe9f4ff,0x334733,2.2));const sun=new THREE.DirectionalLight(0xffe9c4,3);sun.position.set(-700,1200,-500);scene.add(sun);
const route=new TrackFrameSampler(data.points.map(p=>new THREE.Vector3(p.x,p.y+.55,p.z)));
const vertices:number[]=[],indices:number[]=[];
for(let row=0;row<terrain.height;row++)for(let col=0;col<terrain.width;col++)vertices.push(terrain.originX+col*terrain.spacingM,terrain.heights[row*terrain.width+col],terrain.originZ+row*terrain.spacingM);
for(let row=0;row<terrain.height-1;row++)for(let col=0;col<terrain.width-1;col++){const a=row*terrain.width+col,b=a+terrain.width,d=b+1,e=a+1;indices.push(a,b,d,a,d,e)}
const terrainGeo=new THREE.BufferGeometry();terrainGeo.setAttribute('position',new THREE.Float32BufferAttribute(vertices,3));terrainGeo.setIndex(indices);terrainGeo.computeVertexNormals();terrainGeo.computeBoundingSphere();const terrainMesh=new THREE.Mesh(terrainGeo,new THREE.MeshStandardMaterial({color:0x628650,roughness:1}));terrainMesh.name='terrain-grid';scene.add(terrainMesh);

// Derived formation: trapezoidal ballast establishes terrain → bed → sleepers → rails.
const bedVertices:number[]=[],bedIndices:number[]=[],bedStep=5,bedRows=Math.ceil(route.length/bedStep)+1;
for(let i=0;i<bedRows;i++){const f=route.sample(Math.min(route.length,i*bedStep));for(const [lateral,vertical] of [[-2.75,-.28],[-1.8,0],[1.8,0],[2.75,-.28]]){const p=f.position.clone().addScaledVector(f.right,lateral).addScaledVector(f.up,vertical);bedVertices.push(p.x,p.y,p.z)}}
for(let i=0;i<bedRows-1;i++)for(let c=0;c<3;c++){const a=i*4+c,b=a+4,d=b+1,e=a+1;bedIndices.push(a,b,d,a,d,e)}
const bedGeo=new THREE.BufferGeometry();bedGeo.setAttribute('position',new THREE.Float32BufferAttribute(bedVertices,3));bedGeo.setIndex(bedIndices);bedGeo.computeVertexNormals();scene.add(new THREE.Mesh(bedGeo,new THREE.MeshStandardMaterial({color:0x7a7165,roughness:1})));

function offsetCurve(lateral:number,vertical:number){const points:THREE.Vector3[]=[];for(let s=0;s<=route.length;s+=5)points.push(route.offsetPoint(s,lateral,vertical));points.push(route.offsetPoint(route.length,lateral,vertical));return new THREE.CatmullRomCurve3(points,false,'centripetal',.1)}
const railMaterial=new THREE.MeshStandardMaterial({color:0xc4c8c6,metalness:.85,roughness:.25});for(const lateral of [-.7175,.7175])scene.add(new THREE.Mesh(new THREE.TubeGeometry(offsetCurve(lateral,.22),Math.ceil(route.length/5),.07,6,false),railMaterial));
const dummy=new THREE.Object3D(),sleepers=new THREE.InstancedMesh(new THREE.BoxGeometry(2.7,.14,.24),new THREE.MeshStandardMaterial({color:0x463a31}),Math.floor(route.length/3));
for(let i=0;i<sleepers.count;i++){const f=route.sample(i/(sleepers.count-1)*route.length);dummy.position.copy(f.position).addScaledVector(f.up,.08);dummy.quaternion.copy(f.orientation);dummy.updateMatrix();sleepers.setMatrixAt(i,dummy.matrix)}scene.add(sleepers);
const mastMat=new THREE.MeshStandardMaterial({color:0x55615b}),mastSpacing=55,mastCount=Math.floor(route.length/mastSpacing)+1,masts=new THREE.InstancedMesh(new THREE.CylinderGeometry(.07,.1,7,6),mastMat,mastCount),mastPoints:THREE.Vector3[]=[];
for(let i=0;i<mastCount;i++){const f=route.sample(Math.min(route.length,i*mastSpacing)),p=f.position.clone().addScaledVector(f.right,3.1).add(new THREE.Vector3(0,3.5,0));mastPoints.push(p.clone().add(new THREE.Vector3(0,3.1,0)));dummy.position.copy(p);dummy.quaternion.identity();dummy.updateMatrix();masts.setMatrixAt(i,dummy.matrix)}scene.add(masts);scene.add(new THREE.Mesh(new THREE.TubeGeometry(new THREE.CatmullRomCurve3(mastPoints),mastPoints.length*2,.025,4,false),new THREE.MeshStandardMaterial({color:0x303735})));
const signalAnchors:THREE.Vector3[]=[];data.signals.forEach((signal,i)=>{const f=route.sample(signal.s),direction=signal.tags.direction==='backward'?-1:1,p=f.position.clone().addScaledVector(f.right,2.65);signalAnchors.push(p);const g=new THREE.Group(),post=new THREE.Mesh(new THREE.CylinderGeometry(.06,.08,4,6),mastMat),head=new THREE.Mesh(new THREE.BoxGeometry(.65,1.5,.35),new THREE.MeshStandardMaterial({color:0x151918})),lamp=new THREE.Mesh(new THREE.SphereGeometry(.17,10,10),new THREE.MeshStandardMaterial({color:i%5?0x48e46e:0xff2b22,emissive:i%5?0x20b448:0xff180f,emissiveIntensity:3}));post.position.y=2;head.position.y=4.3;lamp.position.set(0,4.3,-.2*direction);g.add(post,head,lamp);g.position.copy(p);const facing=f.orientation.clone();if(direction<0)facing.multiply(new THREE.Quaternion().setFromAxisAngle(new THREE.Vector3(0,1,0),Math.PI));g.quaternion.copy(facing);scene.add(g)});

const TRAIN={length:24,width:3,height:3.6,frontOffset:10.5,eyeHeight:3.25};
const train=new THREE.Group(),bodyMat=new THREE.MeshStandardMaterial({color:0xdadfdd}),body=new THREE.Mesh(new THREE.BoxGeometry(TRAIN.width,TRAIN.height,TRAIN.length),bodyMat),stripe=new THREE.Mesh(new THREE.BoxGeometry(3.06,1,18),new THREE.MeshStandardMaterial({color:0xc92d2b}));body.position.y=2.05;stripe.position.set(0,1.6,0);train.add(body,stripe);
const glass=new THREE.MeshStandardMaterial({color:0x172b32,metalness:.2,roughness:.2});for(const z of [-12.03,12.03]){const screen=new THREE.Mesh(new THREE.BoxGeometry(2.35,1,.06),glass);screen.position.set(0,2.65,z);train.add(screen)}
const wheelMat=new THREE.MeshStandardMaterial({color:0x202422,metalness:.6}),wheelGeo=new THREE.CylinderGeometry(.45,.45,.22,16);wheelGeo.rotateZ(Math.PI/2);for(const z of [-8,8])for(const x of [-1.35,1.35]){const w=new THREE.Mesh(wheelGeo,wheelMat);w.position.set(x,.55,z);train.add(w)}scene.add(train);
if(debug){const debugGroup=new THREE.Group();for(let s=0;s<=route.length;s+=250){const f=route.sample(s);debugGroup.add(new THREE.ArrowHelper(f.tangent,f.position,12,0x2ea8ff),new THREE.ArrowHelper(f.right,f.position,8,0xffc52e))}for(const p of signalAnchors){const marker=new THREE.Mesh(new THREE.SphereGeometry(.35),new THREE.MeshBasicMaterial({color:0xff33dd}));marker.position.copy(p);debugGroup.add(marker)}scene.add(debugGroup)}

const sim=new TrainSim();let power=0,brake=0,mode=params.get('camera')==='chase'?1:0,last=performance.now(),acc=0,score=1000,camReady=false,frames=0,fpsAt=performance.now();const el=(id:string)=>document.querySelector<HTMLElement>('#'+id)!;const next=(a:Obj[],s:number)=>a.filter(x=>x.s>s+5).sort((x,y)=>x.s-y.s)[0];
addEventListener('keydown',e=>{if(e.repeat)return;if(['w','ArrowUp'].includes(e.key)){power=Math.min(5,power+1);brake=0}if(['s','ArrowDown'].includes(e.key)){brake=Math.min(5,brake+1);power=0}if(e.key==='a'){power=Math.max(0,power-1);brake=Math.max(0,brake-1)}if(e.code==='Space'){brake=6;power=0;score-=50}if(e.key==='r'){sim.reset();power=brake=0;score=1000}if(e.key==='c'){mode=(mode+1)%2;camReady=false}});el('drive').onclick=()=>el('start').classList.add('hidden');el('dataBtn').onclick=()=>el('inspector').classList.remove('hidden');el('close').onclick=()=>el('inspector').classList.add('hidden');if(debug)el('start').classList.add('hidden');
function frame(now:number){const dt=Math.min((now-last)/1000,.1);last=now;acc+=dt;const s=THREE.MathUtils.clamp(fixedS??sim.position(),0,route.length-1),f=route.sample(s);if(fixedS===null){sim.set_controls(power,brake);while(acc>=1/120){sim.step(1/120,f.gradientPermille);acc-=1/120}}train.position.copy(f.position);train.quaternion.copy(f.orientation);train.visible=mode!==0;
  const desired=mode===0?route.sample(Math.min(route.length,s+TRAIN.frontOffset)).position.clone().addScaledVector(f.up,TRAIN.eyeHeight):f.position.clone().addScaledVector(f.tangent,-30).addScaledVector(f.right,7).add(new THREE.Vector3(0,10,0));
  const target=mode===0?f.position.clone().addScaledVector(f.tangent,100).addScaledVector(f.up,TRAIN.eyeHeight):f.position.clone().addScaledVector(f.tangent,5).addScaledVector(f.up,2);
  if(!camReady){camera.position.copy(desired);camReady=true}else camera.position.lerp(desired,1-Math.exp(-dt*7));camera.up.copy(f.up);camera.lookAt(target);
  const limits=data.speedLimits.filter(x=>s>=x.start-80&&s<=x.end+80),limit=limits.length?Math.min(...limits.map(x=>x.speed)):80,sig=next(data.signals,s),station=next(data.stations,s);if(sim.speed()*3.6>limit+3)score-=dt*.4;el('speed').textContent=(fixedS===null?sim.speed()*3.6:0).toFixed(0);el('limit').textContent=''+limit;el('notch').textContent=`P${power} / B${brake===6?'E':brake}`;el('grade').textContent=`${f.gradientPermille.toFixed(1)} ‰`;el('signal').textContent=sig?`${sig.s-s<700?'HALT':'CLEAR'} ${(sig.s-s).toFixed(0)} m`:'END';el('station').textContent=station?`${station.tags.name??'mapped stop'} ${(station.s-s).toFixed(0)} m`:'Uznach';el('details').innerHTML=`<b>Train telemetry</b><p>Route s: ${s.toFixed(1)} m<br>Acceleration: ${sim.acceleration().toFixed(2)} m/s²<br>Energy: ${sim.energy_used_kwh().toFixed(1)} kWh<br>Score: ${score.toFixed(0)}</p>`;
  if(debug){frames++;if(now-fpsAt>500){el('debugStats').textContent=`s ${s.toFixed(0)} m · ${(frames*1000/(now-fpsAt)).toFixed(0)} fps · ${renderer.info.render.calls} draws · ${renderer.info.render.triangles.toLocaleString()} triangles`;frames=0;fpsAt=now}}
  renderer.render(scene,camera);requestAnimationFrame(frame)}requestAnimationFrame(frame);addEventListener('resize',()=>{camera.aspect=innerWidth/innerHeight;camera.updateProjectionMatrix();renderer.setSize(innerWidth,innerHeight)});
