import * as THREE from 'three';import type {RailNetwork,RailEdge} from './rail-network';
export type TrafficCall={name:string;platform:string;arrival:string;departure:string;sequence:number};export type AiService={id:string;tripId:string;publicName:string;headsign:string;direction:string;stops:TrafficCall[];path:{edgeId:string;reverse:boolean}[];timetableClassification:string;pathClassification:string;motionClassification:string};export type TrafficData={version:number;id:string;name:string;serviceDate:string;feed:string;publisher:string;window:{start:string;end:string};playerTripId:string;services:AiService[]};
type PathPoint={position:THREE.Vector3;distance:number;edgeId:string};export type AiState={id:string;service:AiService;position:THREE.Vector3;tangent:THREE.Vector3;speedMps:number;pathDistance:number;occupiedEdges:string[];active:boolean;dwelling:boolean;nextStop:string};
const seconds=(value:string)=>{const [h,m,s]=value.split(':').map(Number);return h*3600+m*60+s};
export class TrafficSimulation{
  private paths=new Map<string,PathPoint[]>();states:AiState[]=[];
  constructor(readonly data:TrafficData,network:RailNetwork,readonly stationS:Record<string,number>,readonly routeLength:number){const edges=new Map(network.edges.map(e=>[e.id,e]));for(const service of data.services)this.paths.set(service.id,this.makePath(service,edges))}
  private makePath(service:AiService,edges:Map<string,RailEdge>){const result:PathPoint[]=[];let distance=0;for(const part of service.path){const edge=edges.get(part.edgeId);if(!edge)throw Error(`missing AI edge ${part.edgeId}`);const points=(part.reverse?[...edge.points].reverse():edge.points).map(p=>new THREE.Vector3(...p));for(const p of points){if(result.length&&p.distanceTo(result.at(-1)!.position)<.05)continue;if(result.length)distance+=p.distanceTo(result.at(-1)!.position);result.push({position:p,distance,edgeId:edge.id})}}if(result.length<2)throw Error(`empty AI path ${service.id}`);return result}
  private sample(path:PathPoint[],distance:number){let i=0;while(i<path.length-2&&path[i+1].distance<distance)i++;const a=path[i],b=path[i+1],t=Math.max(0,Math.min(1,(distance-a.distance)/(b.distance-a.distance||1)));return {position:a.position.clone().lerp(b.position,t),tangent:b.position.clone().sub(a.position).normalize(),edgeId:t<.5?a.edgeId:b.edgeId,index:i}}
  update(clockSeconds:number){this.states=this.data.services.map(service=>{const path=this.paths.get(service.id)!,length=path.at(-1)!.distance,forward=service.direction.startsWith('Rapperswil'),distanceFor=(name:string)=>{const fraction=(this.stationS[name]??0)/this.routeLength;return (forward?fraction:1-fraction)*length};let distance=0,speed=0,dwelling=false,nextStop=service.stops[0]?.name??'',active=false;
      for(let i=0;i<service.stops.length;i++){const stop=service.stops[i],arrival=seconds(stop.arrival),departure=seconds(stop.departure);if(clockSeconds>=arrival&&clockSeconds<=departure){distance=distanceFor(stop.name);dwelling=true;active=true;nextStop=stop.name;break}const next=service.stops[i+1];if(next&&clockSeconds>departure&&clockSeconds<seconds(next.arrival)){const start=distanceFor(stop.name),end=distanceFor(next.name),duration=seconds(next.arrival)-departure,elapsed=clockSeconds-departure,D=Math.abs(end-start),ta=Math.min(25,duration*.25),v=D/Math.max(1,duration-ta),direction=Math.sign(end-start);let travelled;if(elapsed<ta)travelled=.5*(v/ta)*elapsed*elapsed;else if(elapsed>duration-ta){const rem=duration-elapsed;travelled=D-.5*(v/ta)*rem*rem}else travelled=.5*v*ta+v*(elapsed-ta);distance=start+direction*travelled;speed=(elapsed<ta?v/ta*elapsed:elapsed>duration-ta?v/ta*(duration-elapsed):v);active=true;nextStop=next.name;break}}
      const first=service.stops[0],last=service.stops.at(-1)!;if(clockSeconds<seconds(first.arrival)){distance=distanceFor(first.name);nextStop=first.name}else if(clockSeconds>seconds(last.departure)){distance=distanceFor(last.name);nextStop=last.name}const front=this.sample(path,distance),rear=this.sample(path,Math.max(0,distance-75)),occupied=[...new Set(path.slice(rear.index,front.index+2).map(p=>p.edgeId))];return {id:service.id,service,position:front.position,tangent:front.tangent,speedMps:speed,pathDistance:distance,occupiedEdges:occupied,active,dwelling,nextStop}});return this.states}
  reset(){this.states=[]}
}
