import type {WeatherState} from './environment';
export interface WeatherSample {seconds:number;temperatureC:number;relativeHumidity:number;precipitationMmH:number;windSpeedMps:number;windDirectionDeg:number;cloudCoverDerived:number;visibilityMDerived:number}
export interface WeatherStation {id:string;name:string;latitude:number;longitude:number;samples:WeatherSample[]}
export interface WeatherFieldData {schemaVersion:number;date:string;source:string;sourceCollection:string;retrieved:string;license:string;observedVariables:string[];derivedVariables:string[];stations:WeatherStation[]}
const clamp=(v:number,a=0,b=1)=>Math.max(a,Math.min(b,v));
function temporal(station:WeatherStation,seconds:number){let a=station.samples[0],b=station.samples.at(-1)!;for(let i=1;i<station.samples.length;i++)if(station.samples[i].seconds>=seconds){a=station.samples[i-1];b=station.samples[i];break}const t=clamp((seconds-a.seconds)/Math.max(1,b.seconds-a.seconds));return {temperatureC:a.temperatureC+(b.temperatureC-a.temperatureC)*t,relativeHumidity:a.relativeHumidity+(b.relativeHumidity-a.relativeHumidity)*t,precipitationMmH:a.precipitationMmH+(b.precipitationMmH-a.precipitationMmH)*t,windSpeedMps:a.windSpeedMps+(b.windSpeedMps-a.windSpeedMps)*t,windDirectionDeg:a.windDirectionDeg+(b.windDirectionDeg-a.windDirectionDeg)*t,cloudCover:a.cloudCoverDerived+(b.cloudCoverDerived-a.cloudCoverDerived)*t,visibilityM:a.visibilityMDerived+(b.visibilityMDerived-a.visibilityMDerived)*t}}
export function sampleWeatherField(field:WeatherFieldData,latitude:number,longitude:number,seconds:number):WeatherState{
  const nearby=field.stations.map(station=>({station,distance:Math.max(.01,Math.hypot((station.latitude-latitude)*111,(station.longitude-longitude)*75))})).sort((a,b)=>a.distance-b.distance).slice(0,3),weights=nearby.map(x=>1/(x.distance*x.distance)),total=weights.reduce((a,b)=>a+b,0),samples=nearby.map(x=>temporal(x.station,seconds)),average=(key:keyof ReturnType<typeof temporal>)=>samples.reduce((sum,sample,i)=>sum+(sample[key] as number)*weights[i],0)/total;
  const precipitationMmH=average('precipitationMmH'),temperatureC=average('temperatureC');return {preset:precipitationMmH>4?'heavy-rain':precipitationMmH>.05?'rain':average('cloudCover')>.75?'overcast':'clear',temperatureC,precipitationMmH,cloudCover:clamp(average('cloudCover')),windSpeedMps:average('windSpeedMps'),windDirectionDeg:average('windDirectionDeg'),visibilityM:average('visibilityM'),relativeHumidity:clamp(average('relativeHumidity')),source:'HISTORICAL',sourceTimestamp:`${field.date} / hourly observations`}
}
